import React from "react";
import { BsArrowRight } from "react-icons/bs";
import release1 from "../assets/385m.png";
import release2 from "../assets/500m.png";
import Card from "./Card";

export default function Release() {
  return (
    <div className="releases" id="features">
      <div className="release orange">
        <div className="content">
          <h2 className="title"> Utility-Based NFTs </h2>
          <p className="description">
          Pixieverse NFTs aren't just static images or animations
          </p>
          <p className="description">
          they're keys to unlock a myriad of utilities and revenue streams within our ecosystem.
          </p>
          <p className="description">80% of our Ecosystem  proceeds go to Our Nft Holders.</p>
          <a href="#mint" className="link">
            Check them out <BsArrowRight />
          </a>
        </div>
        <div className="image">
          <img src={release1} alt="release" />
          <div className="ellipse pink"></div>
        </div>
      </div>
      <div className="release green">
        <div className="card-container">
          <Card
            image={release2}
            series="Gloop Series"
            title="Purple Man"
            price={3.95}
            tag="1094"
            time={2}
          />
          <div className="ellipse orange"></div>
        </div>
        <div className="content">
          <h2 className="title"> Passive Income</h2>
          <p className="description">
          As a Pixieverse NFT holder, you're not just a collector
          </p>
          <p> you're a stakeholder in our digital universe. Earn passive income from the revenues generated by our dApps, distributed to NFT holders monthly.
          </p>
          <p className="description">80% of our Ecosystem  proceeds go to Our Nft Holders.</p>
          <a href="#mint" className="link">
            Check them out <BsArrowRight />
          </a>
        </div>
      </div>
    </div>
  );
}
